import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Modal,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View} from 'react-native';
import {useNavigation} from '@react-navigation/native';
import {activityApi} from '../../api/activityApi';

const TYPES=[['nukkad','NUKKAD MEETS','#117b63'],['influencer','INFLUENCER MEETS','#842849'],['farmer','FARMER MEETS','#ad6807'],['retailer','RETAILER MEETS','#4c60b8']] as const;
const RANGE=[{id:'today',name:'Today'},{id:'month',name:'This month'},{id:'year',name:'This year'}];
const ZERO={meets:0,participants:0,gifts:0,expense:0};

export default function ActivitySummaryScreen(){
  const nav=useNavigation<any>();const [role,setRole]=useState<'asr'|'dsr'>('asr');const [range,setRange]=useState('month');const [zone,setZone]=useState<any>();const [branch,setBranch]=useState<any>();const [distributor,setDistributor]=useState<any>();const [data,setData]=useState<any>();const [loading,setLoading]=useState(false);const [picker,setPicker]=useState<any>();
  const load=useCallback(async()=>{setLoading(true);try{const r=await activityApi.summary({date_range:range,role,zone:zone?.id,branch:branch?.id,distributor:distributor?.id});setData(r.data.data)}catch{setData({rows:[],filters:{}})}finally{setLoading(false)}},[range,role,zone,branch,distributor]);
  useEffect(()=>{load()},[load]);const rows=useMemo(()=>data?.rows||[],[data?.rows]);const grand=useMemo(()=>sumRows(rows),[rows]);
  const displayRows=useMemo(()=>{let sr=0;const zones=[...new Set(rows.map((x:any)=>x.zone||'Unassigned'))];return zones.flatMap(zone=>{const zoneRows=rows.filter((x:any)=>(x.zone||'Unassigned')===zone);return [...zoneRows.map((row:any)=>({kind:'data',row,sr:++sr})),{kind:'subtotal',zone,summary:sumRows(zoneRows)}]})},[rows]);
  const choose=(title:string,items:any[],value:any,setter:any)=>setPicker({title,items,value,setter});
  return <SafeAreaView style={s.page}>
    <View style={s.header}><Pressable onPress={()=>nav.goBack()}><Text style={s.back}>‹</Text></Pressable><View><Text style={s.over}>FIELDKONNECT · SUMMARY</Text><Text style={s.title}>Meeting summary — distributor wise</Text></View></View>
    <ScrollView><View style={s.filters}>
      <Select label="DATE RANGE" text={RANGE.find(x=>x.id===range)?.name||''} onPress={()=>choose('Date range',RANGE,{id:range},(x:any)=>setRange(x.id))}/>
      <Select label="ZONE" text={zone?.name||'All zones'} onPress={()=>choose('Zone',[{id:null,name:'All zones'},...(data?.filters?.zones||[]).map((x:string)=>({id:x,name:x}))],zone,setZone)}/>
      <Select label="BO" text={branch?.name||'All BO'} onPress={()=>choose('BO',[{id:null,name:'All BO'},...(data?.filters?.branches||[])],branch,setBranch)}/>
      <Select label="DISTRIBUTOR" text={distributor?.name||'All distributors'} onPress={()=>choose('Distributor',[{id:null,name:'All distributors'},...(data?.filters?.distributors||[])],distributor,setDistributor)}/>
    </View>
    <View style={s.tabs}>{(['asr','dsr'] as const).map(x=><Pressable key={x} style={[s.tab,role===x&&s.tabOn]} onPress={()=>setRole(x)}><Text style={[s.tabText,role===x&&s.white]}>{x.toUpperCase()}</Text></Pressable>)}</View>
    {loading?<ActivityIndicator style={{height:300}} color="#3d50aa"/>:<View style={s.tableFrame}>
      <View style={s.fixedColumns}>
        <View style={s.row}><Cell text="SR" w={42} head/><Cell text="ZONE" w={70} head/></View>
        {displayRows.map((item:any,i:number)=>item.kind==='data'?<View style={s.row} key={`fixed-${item.row.user_id}-${item.row.distributor_id}-${i}`}><Cell text={String(item.sr)} w={42}/><Cell text={item.row.zone} w={70}/></View>:<View style={s.row} key={`fixed-sub-${item.zone}`}><Cell text="" w={42} subtotal/><Cell text={item.zone} w={70} subtotal/></View>)}
        <View style={s.row}><Cell text="" w={42} head/><Cell text="TOTAL" w={70} head/></View>
      </View>
      <ScrollView horizontal showsHorizontalScrollIndicator style={s.scrollTable}><View>
        <View style={s.row}><Cell text="BRANCH" w={105} head/><Cell text="DISTRIBUTOR" w={130} head/><Cell text={role.toUpperCase()} w={110} head/><Cell text="SALES ENGG" w={120} head/>{TYPES.map(x=><MetricHead key={x[0]} label={x[1]} color={x[2]}/>)}<MetricHead label="TOTAL" color="#30428f"/></View>
        {displayRows.map((item:any,i:number)=>item.kind==='data'?<View style={s.row} key={`${item.row.user_id}-${item.row.distributor_id}-${i}`}><Cell text={item.row.branch} w={105}/><Cell text={item.row.distributor_name} w={130}/><Cell text={`${item.row.employee_code||''}\n${item.row.user_name||''}`} w={110}/><Cell text={item.row.manager||'-'} w={120}/>{TYPES.map(x=><Metric key={x[0]} value={item.row[x[0]]}/>) }<Metric value={item.row.total} total/></View>:<View style={s.row} key={`sub-${item.zone}`}><Cell text="ZONE SUBTOTAL" w={465} subtotal/>{TYPES.map(x=><Metric key={x[0]} value={item.summary[x[0]]} subtotal/>)}<Metric value={item.summary.total} subtotal/></View>)}
        <View style={[s.row,s.grand]}><Cell text="GRAND TOTAL" w={465} head/>{TYPES.map(x=><Metric key={x[0]} value={grand[x[0]]} total/>)}<Metric value={grand.total} total/></View>
      </View></ScrollView>
    </View>}
    </ScrollView>
    <Modal visible={!!picker} transparent animationType="fade" onRequestClose={()=>setPicker(null)}><Pressable style={s.overlay} onPress={()=>setPicker(null)}><View style={s.sheet}><Text style={s.sheetTitle}>{picker?.title}</Text><ScrollView style={{maxHeight:420}}>{(picker?.items||[]).map((x:any,i:number)=><Pressable style={s.option} key={`${x.id}-${i}`} onPress={()=>{picker.setter(x.id===null?null:x);setPicker(null)}}><Text style={s.optionText}>{x.name}</Text></Pressable>)}</ScrollView></View></Pressable></Modal>
  </SafeAreaView>
}
function Select({label,text,onPress}:any){return <View style={s.selectWrap}><Text style={s.label}>{label}</Text><Pressable style={s.select} onPress={onPress}><Text numberOfLines={1} style={s.selectText}>{text}</Text><Text>⌄</Text></Pressable></View>}
function Cell({text,w,head,subtotal}:any){return <View style={[s.cell,{width:w},head&&s.headCell,subtotal&&s.subtotalCell]}><Text style={[s.cellText,head&&s.white,subtotal&&s.subtotalText]}>{text||'-'}</Text></View>}
function MetricHead({label,color}:any){return <View><View style={[s.groupHead,{backgroundColor:color}]}><Text style={s.white}>{label}</Text></View><View style={s.row}>{['MTS','PART.','GIFT','EXP ₹'].map(x=><View key={x} style={[s.miniHead,{backgroundColor:color}]}><Text style={s.miniText}>{x}</Text></View>)}</View></View>}
function Metric({value=ZERO,total,subtotal}:any){return <View style={s.row}>{['meets','participants','gifts','expense'].map(k=><View key={k} style={[s.metric,total&&s.totalCell,subtotal&&s.subtotalCell]}><Text style={[s.cellText,total&&s.totalText,subtotal&&s.subtotalText]}>{k==='expense'?`₹${Number(value?.[k]||0).toLocaleString('en-IN')}`:value?.[k]||0}</Text></View>)}</View>}
function sumRows(rows:any[]){const out:any={};for(const [key] of TYPES)out[key]={...ZERO};out.total={...ZERO};for(const r of rows){for(const [key] of TYPES)for(const k of Object.keys(ZERO))out[key][k]+=Number(r[key]?.[k]||0);for(const k of Object.keys(ZERO))out.total[k]+=Number(r.total?.[k]||0)}return out}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f3f4f9'},header:{backgroundColor:'#3d50aa',padding:18,flexDirection:'row',alignItems:'center',gap:14},back:{color:'#fff',fontSize:42,lineHeight:42},over:{color:'#cdd4ff',fontSize:11,fontWeight:'700'},title:{color:'#fff',fontSize:19,fontWeight:'700'},filters:{padding:12,flexDirection:'row',flexWrap:'wrap',gap:10,backgroundColor:'#fff'},selectWrap:{width:'48%'},label:{fontSize:10,fontWeight:'700',color:'#667085',marginBottom:5},select:{borderWidth:1,borderColor:'#cbd2e8',borderRadius:9,height:46,paddingHorizontal:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},selectText:{fontSize:14,maxWidth:'88%'},tabs:{flexDirection:'row',padding:12,gap:8,backgroundColor:'#fff'},tab:{flex:1,backgroundColor:'#eceef5',borderRadius:24,padding:12,alignItems:'center'},tabOn:{backgroundColor:'#3d50aa'},tabText:{fontWeight:'700',color:'#697080'},white:{color:'#fff',fontWeight:'700'},tableFrame:{margin:12,borderRadius:10,overflow:'hidden',flexDirection:'row'},fixedColumns:{width:112,zIndex:2,elevation:3},scrollTable:{flex:1},row:{flexDirection:'row'},cell:{height:62,borderWidth:.5,borderColor:'#d7dbea',padding:6,justifyContent:'center',backgroundColor:'#fff'},headCell:{backgroundColor:'#4053aa'},cellText:{fontSize:11,color:'#202838'},groupHead:{width:280,height:32,alignItems:'center',justifyContent:'center'},miniHead:{width:70,height:30,alignItems:'center',justifyContent:'center',borderWidth:.5,borderColor:'#ffffff44'},miniText:{fontSize:9,color:'#fff',fontWeight:'700'},metric:{width:70,height:62,backgroundColor:'#fff',borderWidth:.5,borderColor:'#d7dbea',alignItems:'center',justifyContent:'center'},totalCell:{backgroundColor:'#f5f6fc'},totalText:{color:'#3548a0',fontWeight:'700'},subtotalCell:{backgroundColor:'#fff1d6',borderTopColor:'#bd720b',borderTopWidth:1.5},subtotalText:{color:'#683c08',fontWeight:'700'},grand:{backgroundColor:'#30428f'},overlay:{flex:1,backgroundColor:'#0008',justifyContent:'flex-end'},sheet:{backgroundColor:'#fff',borderTopLeftRadius:22,borderTopRightRadius:22,padding:20},sheetTitle:{fontSize:18,fontWeight:'700',marginBottom:12},option:{paddingVertical:15,borderBottomWidth:1,borderColor:'#eee'},optionText:{fontSize:16}});
